## simplifying keyword combinations
KW<-str_remove_all(KW,'^ ') # remove leading spaces
KW<-str_remove_all(KW,' $') # remove trailing spaces
KW<-tolower(KW)
KW<-str_remove_all(KW,'^music ') # remove music
KW[str_detect(KW,'^musical ')]<-''

KW<-str_remove_all(KW,'ê') # remove garbage
KW<-str_remove_all(KW,'�') # remove garbage
KW<-str_remove_all(KW,'s$') # remove plurals
KW<-str_remove_all(KW,'ology$') # Methodology to method
KW<-str_remove_all(KW,'^\n') # Methodology to method
KW<-str_replace_all(KW,'stres','stress') # remove plurals
KW<-str_replace_all(KW,'sadnes','sadness') # remove plurals
KW<-str_replace_all(KW,'analysi','analysis') # remove plurals
KW<-str_replace_all(KW,'loudnes','loudness') # remove plurals
KW<-str_replace_all(KW,'aesthetic','aesthetics') # remove plurals
KW<-str_replace_all(KW,'psychophysi','psychophysiology') # remove plurals
KW<-stringi::stri_trans_general(KW,"latin-ascii")

KW[str_detect(KW,'embodied|embodiment')]<-'embodied'
KW[str_detect(KW,'expect')]<-'expectancy'
KW[str_detect(KW,'expertise|experise')]<-'expertise'
KW[str_detect(KW,'emotional intelligence')]<-'emotional intelligence'
KW[str_detect(KW,'early childhood')]<-'early childhood'
KW[str_detect(KW,'early')]<-'early'
KW[str_detect(KW,'dimension')]<-'emotion'
KW[str_detect(KW,'dance')]<-'dance'
KW[str_detect(KW,'cross-cul|cross cul')]<-'cross-cultural'
KW[str_detect(KW,'cross-modal|cross modal|crossmodal')]<-'cross-modal'
KW[str_detect(KW,'culture')]<-'culture'
KW[str_detect(KW,'^cultural')]<-'culture'
KW[str_detect(KW,'creativ')]<-'creativity'
KW[str_detect(KW,'coping')]<-'coping'
KW[str_detect(KW,'continuous')]<-'continuous'
KW[str_detect(KW,'contemporary')]<-'contemporary'
KW[str_detect(KW,'consumer')]<-'consumer'
KW[str_detect(KW,'conservat')]<-'conservatory'
KW[str_detect(KW,'conduct')]<-'conducting'
KW[str_detect(KW,'concert')]<-'concert'
KW[str_detect(KW,'conceptual')]<-'conceptual'
KW[str_detect(KW,'computational')]<-'computational'
KW[str_detect(KW,'compositi')]<-'composition'
KW[str_detect(KW,'community')]<-'community'
KW[str_detect(KW,'communication|communicaiton')]<-'communication'
KW[str_detect(KW,'collective')]<-'collective'
KW[str_detect(KW,'cognitive')]<-'cognitive'
KW[str_detect(KW,'compositi')]<-'composition'
KW[str_detect(KW,'compositi')]<-'composition'
KW[str_detect(KW,'compositi')]<-'composition'
KW[str_detect(KW,'affect|mood|felt|feel|emotional|discrete emotion|emotion induction|expressed|emotion loc|emotion model|emotion recog|emotion perc')]<-'emotion'
KW[str_detect(KW,'chord')]<-'chord'
KW[str_detect(KW,'favo')]<-'favourite'
KW[str_detect(KW,'face|facial')]<-'facial'
KW[str_detect(KW,'extramusical')]<-'extramusical'
KW[str_detect(KW,'expressivenes|expressivity|expression')]<-'expression'
KW[str_detect(KW,'expertise|expert')]<-'expertise'
KW[str_detect(KW,'everyday')]<-'everyday'
KW[str_detect(KW,'groove')]<-'groove'
KW[str_detect(KW,'ensemble')]<-'ensemble'
KW[str_detect(KW,'groove')]<-'groove'
KW[str_detect(KW,'congruen|incongruen')]<-'congruence'
KW[str_detect(KW,'consonance|consonant|disson')]<-'consonance'
KW[str_detect(KW,'context')]<-'context'
KW[str_detect(KW,'corpu')]<-'corpus'
KW[str_detect(KW,'decision')]<-'decision-making'
KW[str_detect(KW,'depress')]<-'depression'
KW[str_detect(KW,'digital')]<-'digital'
KW[str_detect(KW,'^education')]<-'education'
KW[str_detect(KW,'empat')]<-'empathy'
KW[str_detect(KW,'eye')]<-'eye-tracking'
KW[str_detect(KW,'enactive|enaction')]<-'enactive'
KW[str_detect(KW,'experience sampling method')]<-'experience sampling'
KW[str_detect(KW,'^family')]<-'family'
KW[str_detect(KW,'film')]<-'film music'
KW[str_detect(KW,'^flow')]<-'flow'
KW[str_detect(KW,'^form per|structur|onata form')]<-'form'
KW[str_detect(KW,'^flow')]<-'flow'
KW[str_detect(KW,'^function of music|^functions of music listening')]<-'functions of music'
KW[str_detect(KW,'^gender')]<-'gender'
KW[str_detect(KW,'anxiety')]<-'anxiety'
KW[str_detect(KW,'genre|style')]<-'genre'
KW[str_detect(KW,'anxiety')]<-'anxiety'
KW[str_detect(KW,'gestur')]<-'gesture'
KW[str_detect(KW,'group')]<-'group'
KW[str_detect(KW,'happy')]<-'happy'
KW[str_detect(KW,'harmon')]<-'harmony'
KW[str_detect(KW,'health|well-being')]<-'health'
KW[str_detect(KW,'hearing')]<-'hearing'
KW[str_detect(KW,'heavy')]<-'heavy'
KW[str_detect(KW,'higher education|higher music education')]<-'higher education'
KW[str_detect(KW,'historical per|historically-in|historically inf')]<-'historically-informed performance'
KW[str_detect(KW,'identity|identitie')]<-'identity'
KW[str_detect(KW,'implicit')]<-'implicit'
KW[str_detect(KW,'improvising|improvisation')]<-'improvisation'
KW[str_detect(KW,'individual')]<-'individual'
KW[str_detect(KW,'infant')]<-'infant'
KW[str_detect(KW,'informal')]<-'informal'
KW[str_detect(KW,'implicit')]<-'implicit'
KW[str_detect(KW,'inhibi')]<-'inhibition'
KW[str_detect(KW,'academic achievement|academic achievement in music|academic performance')]<-'academic achievement'
KW[str_detect(KW,'learning')]<-'learning'
KW[str_detect(KW,'involuntary memory|involuntary musical im')]<-'involuntary memory'
KW[str_detect(KW,'ironic')]<-'ironic'
KW[str_detect(KW,'jazz')]<-'jazz'
KW[str_detect(KW,'key')]<-'key'
KW[str_detect(KW,'l2')]<-'l2'
KW[str_detect(KW,'language')]<-'language'
KW[str_detect(KW,'lexical')]<-'lexical'
KW[str_detect(KW,'listener|listening')]<-'listening'
KW[str_detect(KW,'live music')]<-'live music'
KW[str_detect(KW,'longitudinal')]<-'longitudinal'
KW[str_detect(KW,'master clas|master classe|masterclas')]<-'inhibition'
KW[str_detect(KW,'melodic contour|melodic similarity|melodic|melody')]<-'melodic'
KW[str_detect(KW,'memorisation|memorie|memory ')]<-'memory'
KW[str_detect(KW,'imagery')]<-'imagery'
KW[str_detect(KW,'metacognition')]<-'metacognition'
KW[str_detect(KW,'metre|musical meter')]<-'meter'
KW[str_detect(KW,'minor key|minor third')]<-'minor'
KW[str_detect(KW,'mixed method|mixed-method')]<-'mixed method'
KW[str_detect(KW,'modulation type')]<-'modulation'
KW[str_detect(KW,'motion cpature')]<-'motion cpature'
KW[str_detect(KW,'motivic')]<-'motivic'
KW[str_detect(KW,'modulation type')]<-'modulation'
KW[str_detect(KW,'motor')]<-'motor'
KW[str_detect(KW,'movement|movemnet')]<-'movement'
KW[str_detect(KW,'multimodal')]<-'multimodal'
KW[str_detect(KW,'music and emotion|music-evoked emotion')]<-'emotion'
KW[str_detect(KW,'music analysis|musical analysis')]<-'analysis'
KW[str_detect(KW,'abilitie|ability')]<-'ability'
KW[str_detect(KW,'preference')]<-'preference'
KW[str_detect(KW,'musical program|musical programme')]<-'musical program'
KW[str_detect(KW,'neuro')]<-'neural'
KW[str_detect(KW,'non-musician|non-music major|non-music major undergraduate|nonmusician')]<-'non-musician'
KW[str_detect(KW,'occupational')]<-'occupational'
KW[str_detect(KW,'oddball')]<-'oddball'
KW[str_detect(KW,'older|old')]<-'older'
KW[str_detect(KW,'opera')]<-'opera'
KW[str_detect(KW,'orchestral musician|orchestra musician')]<-'orchestral musician'
KW[str_detect(KW,'pain')]<-'pain'
KW[str_detect(KW,'parental')]<-'parental'
KW[str_detect(KW,'parkins')]<-'parkinsons'
KW[str_detect(KW,'perceptual')]<-'perceptual'
KW[str_detect(KW,'percuss')]<-'percussion'
KW[str_detect(KW,'modulation type')]<-'modulation'
KW[str_detect(KW,'performance|performer|performing')]<-'performance'
KW[str_detect(KW,'personality')]<-'personality'
KW[str_detect(KW,'phonological')]<-'phonological'
KW[str_detect(KW,'physical')]<-'physical'
KW[str_detect(KW,'physiological')]<-'physiological'
KW[str_detect(KW,'piano')]<-'piano'
KW[str_detect(KW,'pitch accuracy|pitch')]<-'pitch'
KW[str_detect(KW,'polyph')]<-'polyphony'
KW[str_detect(KW,'pop|pop music|popular song')]<-'popular music'
KW[str_detect(KW,'practice|practic')]<-'practice'
KW[str_detect(KW,'preschool|pre-school')]<-'pre-school'
KW[str_detect(KW,'prevention')]<-'prevention'
KW[str_detect(KW,'principal compone|pca')]<-'principal component'
KW[str_detect(KW,'prison')]<-'prison'
KW[str_detect(KW,'pro-social')]<-'pro-social'
KW[str_detect(KW,'probe tone|probe-tone')]<-'probe tone'
KW[str_detect(KW,'processing')]<-'processing'
KW[str_detect(KW,'professional')]<-'professional'
KW[str_detect(KW,'program note|programme note')]<-'programme note'
KW[str_detect(KW,'psychometric')]<-'psychometric'
KW[str_detect(KW,'pupill|pupilometry')]<-'pupillometry'
KW[str_detect(KW,'qualitative')]<-'qualitative'
KW[str_detect(KW,'rap ')]<-'rap'
KW[str_detect(KW,'rating|rater')]<-'rating'
KW[str_detect(KW,'reading')]<-'reading'
KW[str_detect(KW,'religious')]<-'religious'
KW[str_detect(KW,'rhythm and meter|rhythmic prototype|rhythm')]<-'rhythm'
KW[str_detect(KW,'replication')]<-'replication'
KW[str_detect(KW,'sadness|^sad')]<-'sad'
KW[str_detect(KW,'scale')]<-'scale'
KW[str_detect(KW,'schema')]<-'schema'
KW[str_detect(KW,'school')]<-'school'
KW[str_detect(KW,'segment')]<-'segmentation'
KW[str_detect(KW,'self-det')]<-'self-determination'
KW[str_detect(KW,'self-efficacy')]<-'self-efficacy'
KW[str_detect(KW,'elf-regu')]<-'elf-regulation'
KW[str_detect(KW,'semantic')]<-'semantic'
KW[str_detect(KW,'sensorimotor')]<-'sensorimotor'
KW[str_detect(KW,'sensory')]<-'sensory'
KW[str_detect(KW,'short-term memory|short term memory')]<-'short-term memory'
KW[str_detect(KW,'sight-reading|sightreading')]<-'sight-reading'
KW[str_detect(KW,'singing')]<-'singing'
KW[str_detect(KW,'social')]<-'social'
KW[str_detect(KW,'sociocultural|socio-cultural')]<-'sociocultural'
KW[str_detect(KW,'spatial')]<-'spatial'
KW[str_detect(KW,'speech')]<-'speech'
KW[str_detect(KW,'spontaneou')]<-'spontaneous'
KW[str_detect(KW,'stereotyp')]<-'stereotype'
KW[str_detect(KW,'string')]<-'string'
KW[str_detect(KW,'stroop')]<-'stroop'
KW[str_detect(KW,'timbre')]<-'timbre'
KW[str_detect(KW,'time ')]<-'time'
KW[str_detect(KW,'timing')]<-'timing'
KW[str_detect(KW,'toddler')]<-'toddler'
KW[str_detect(KW,'tonal')]<-'tonal'
KW[str_detect(KW,'training')]<-'training'
KW[str_detect(KW,'transfer')]<-'transfer'
KW[str_detect(KW,'university|undergr')]<-'university'
KW[str_detect(KW,'uses of music|use of music')]<-'uses of music'
KW[str_detect(KW,'verbal')]<-'verbal'
KW[str_detect(KW,'verse-chorus form')]<-'form'
KW[str_detect(KW,'violin|violinist')]<-'violin'
KW[str_detect(KW,'visual')]<-'stereotype'
KW[str_detect(KW,'visuo')]<-'visuo'
KW[str_detect(KW,'vocal')]<-'vocal'
KW[str_detect(KW,'voice')]<-'voice'
KW[str_detect(KW,'web')]<-'web'
KW[str_detect(KW,'musical aptitude')]<-'musical aptitude'
KW[str_detect(KW,'absolute versus|absolute tem')]<-'absolute tempo'
KW[str_detect(KW,'absorption')]<-'absorption'
KW[str_detect(KW,'achievement')]<-'achievement'
KW[str_detect(KW,'acoustic')]<-'acoustic'
KW[str_detect(KW,'adolescent|adolescence')]<-'adolescent'
KW[str_detect(KW,'adult')]<-'adult'
KW[str_detect(KW,'aesthetics')]<-'aesthetics'
KW[str_detect(KW,'aging|ageing')]<-'aging'
KW[str_detect(KW,'alcohol')]<-'alcohol'
KW[str_detect(KW,'alzheime')]<-'alzheimer'
KW[str_detect(KW,'amateur')]<-'amateur'
KW[str_detect(KW,'analytical')]<-'analysis'
KW[str_detect(KW,'and emotion')]<-'emotion'
KW[str_detect(KW,'wellbeing')]<-'health'
KW[str_detect(KW,'anticipation')]<-'expectancy'
KW[str_detect(KW,'attention')]<-'attention'
KW[str_detect(KW,'audience')]<-'audience'
KW[str_detect(KW,'perception')]<-'perception'
KW[str_detect(KW,'autism')]<-'autism'
KW[str_detect(KW,'autobiograp')]<-'autobiograp'
KW[str_detect(KW,'beat')]<-'beat'
KW[str_detect(KW,'big five|personality')]<-'personality'
KW[str_detect(KW,'brecvema')]<-'brecvema'
KW[str_detect(KW,'categor')]<-'categorization'
KW[str_detect(KW,'change')]<-'change'
KW[str_detect(KW,'childhood|child')]<-'children'
KW[str_detect(KW,'circumplex|emotiomn|emotion')]<-'emotion'
KW[str_detect(KW,'cognition')]<-'cognition'
KW[str_detect(KW,'collaborat')]<-'collaborative'
KW[str_detect(KW,'contour')]<-'melody'
KW[str_detect(KW,'cross-secti')]<-'cross-sectional'
KW[str_detect(KW,'developmental')]<-'development'
KW[str_detect(KW,'discourse')]<-'discourse'
KW[str_detect(KW,'earworm')]<-'involuntary memory'
KW[str_detect(KW,'eeg|erp|p3a|n400|mmn|erp|electroencephalography')]<-'eeg'
KW[str_detect(KW,'enculturation')]<-'enculturation'
KW[str_detect(KW,'engagement')]<-'engagement'
KW[str_detect(KW,'executive func')]<-'executive function'
KW[str_detect(KW,'^familiar')]<-'familiarity'
KW[str_detect(KW,'finger tapping')]<-'beat'
KW[str_detect(KW,'^functions of music')]<-'functions of music'
KW[str_detect(KW,'happines')]<-'happy'
KW[str_detect(KW,'^instrument')]<-'instrument'
KW[str_detect(KW,'intercultur')]<-'intercultural'
KW[str_detect(KW,'^interpersonal')]<-'interpersonal'
KW[str_detect(KW,'^interval|perfect fifth|perfect fourth|tritone')]<-'interval'
KW[str_detect(KW,'^intervention')]<-'intervention'
KW[str_detect(KW,'^intrinsic')]<-'intrinsic'
KW[str_detect(KW,'^lifespan|lifespan')]<-'lifespan'
KW[str_detect(KW,'^measurement')]<-'measurement'
KW[str_detect(KW,'^melodie')]<-'melody'
KW[str_detect(KW,'^entrainment')]<-'entrainment'
KW[str_detect(KW,'^mindfulnes')]<-'mindfulness'
KW[str_detect(KW,'^music education')]<-'music education'
KW[str_detect(KW,'retrieval')]<-'mir'
KW[str_detect(KW,'perception')]<-'perception'
KW[str_detect(KW,'^chill')]<-'chill'
KW[str_detect(KW,'development')]<-'development'
KW[str_detect(KW,'^chill')]<-'chill'
KW[str_detect(KW,'tempo')]<-'tempo'
KW[str_detect(KW,'negative emotion in music')]<-'negative emotion'
KW[str_detect(KW,'octave')]<-'octave'
KW[str_detect(KW,'online')]<-'web'
KW[str_detect(KW,'perceived emotion')]<-'emotion'
KW[str_detect(KW,'prejudice')]<-'prejudice'
KW[str_detect(KW,'psychophysiology|psychophysiologyological|pychophysic')]<-'psychophysiology'
KW[str_detect(KW,'quantitative')]<-'quantitative'
KW[str_detect(KW,'regulation|regulator')]<-'regulation'
KW[str_detect(KW,'reminiscence')]<-'reminiscence'
KW[str_detect(KW,'russells model')]<-'emotion'
KW[str_detect(KW,'sensation seeking|sensation-seeking')]<-'sensation seeking'
KW[str_detect(KW,'signal detection theory')]<-'signal detection theory'
KW[str_detect(KW,'song making|song writing|song-writing|songwriting')]<-'song-writing'
KW[str_detect(KW,'substance')]<-'substance'
KW[str_detect(KW,'synchronisation|synchronization|synchron')]<-'synchronization'
KW[str_detect(KW,'teacher|teaching')]<-'teacher'
KW[str_detect(KW,'tempo perception|tempo')]<-'tempo'
KW[str_detect(KW,'tendernes|tension')]<-'emotion'
KW[str_detect(KW,'valence')]<-'emotion'
KW[str_detect(KW,'wellbeing')]<-'wellbeing'
KW[str_detect(KW,'zygonic')]<-'zygonic'

KW <- str_remove_all(KW,'^music$') # remove music

KW[KW==""]<-NA
